name: CMake on Windows

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    
    - name: Check if vcpkg is installed
      run: |
        if (Test-Path -Path "C:\path\to\vcpkg\vcpkg.exe") {
          .\vcpkg\vcpkg.exe --version
        } else {
          echo "vcpkg is not installed."
        }
  
    - name: Set up VCPKG if not installed
      if: failure()
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    # - name: Install vcpkg dependencies
    #   run: |
    #     git clone https://github.com/microsoft/vcpkg.git "C:\vcpkg"
    #     cd "C:\vcpkg"
    #     .\bootstrap-vcpkg.bat
    #     .\vcpkg integrate install
    #     .\vcpkg install freetype harfbuzz glew lua glm bullet3 physfs openal-soft sndfile --triplet x64-windows-static

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }}
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target minimum
