name: CMake on Windows

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target assort
